legend_list = [];
ATH; best_combined_result(core1_rmsd_list, distance_list, peptide_rmsd_list, score_list, "ATH"); legend_list = [legend_list, "ATH"];
ATP; best_combined_result(core1_rmsd_list, distance_list, peptide_rmsd_list, score_list, "ATP"); legend_list = [legend_list, "ATP"];
GTG; best_combined_result(core1_rmsd_list, distance_list, peptide_rmsd_list, score_list, "GTG"); legend_list = [legend_list, "GTG"];
KTW; best_combined_result(core1_rmsd_list, distance_list, peptide_rmsd_list, score_list, "KTW"); legend_list = [legend_list, "KTW"];
LTG; best_combined_result(core1_rmsd_list, distance_list, peptide_rmsd_list, score_list, "LTG"); legend_list = [legend_list, "LTG"];
PTK; best_combined_result(core1_rmsd_list, distance_list, peptide_rmsd_list, score_list, "PTK"); legend_list = [legend_list, "PTK"];
RTP; best_combined_result(core1_rmsd_list, distance_list, peptide_rmsd_list, score_list, "RTP"); legend_list = [legend_list, "RTP"];
STP; best_combined_result(core1_rmsd_list, distance_list, peptide_rmsd_list, score_list, "STP"); legend_list = [legend_list, "STP"];
TTP; best_combined_result(core1_rmsd_list, distance_list, peptide_rmsd_list, score_list, "TTP"); legend_list = [legend_list, "TTP"];
TTT; best_combined_result(core1_rmsd_list, distance_list, peptide_rmsd_list, score_list, "TTT"); legend_list = [legend_list, "TTT"];
WTP; best_combined_result(core1_rmsd_list, distance_list, peptide_rmsd_list, score_list, "WTP"); legend_list = [legend_list, "WTP"];
WTY; best_combined_result(core1_rmsd_list, distance_list, peptide_rmsd_list, score_list, "WTY"); legend_list = [legend_list, "WTY"];
ATY; best_combined_result(core1_rmsd_list, distance_list, peptide_rmsd_list, score_list, "ATY"); legend_list = [legend_list, "ATY"];
ETS; best_combined_result(core1_rmsd_list, distance_list, peptide_rmsd_list, score_list, "ETS"); legend_list = [legend_list, "ETS"];
FTI; best_combined_result(core1_rmsd_list, distance_list, peptide_rmsd_list, score_list, "FTI"); legend_list = [legend_list, "FTI"];
QTR; best_combined_result(core1_rmsd_list, distance_list, peptide_rmsd_list, score_list, "QTR"); legend_list = [legend_list, "QTR"];
YTR; best_combined_result(core1_rmsd_list, distance_list, peptide_rmsd_list, score_list, "YTR"); legend_list = [legend_list, "YTR"];
xlim([0 5]);
legend(legend_list)